# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Azure Pipelines

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: NuGetToolInstaller@1
  displayName: Use NuGet 5.8.x
  inputs:
    versionSpec: 5.8.x
    checkLatest: true
          
- task: NuGetAuthenticate@1
  displayName: NuGet Authenticate
  inputs:
    nuGetServiceConnections: 1533d233-cb15-4a72-98f2-4c6500403486
    forceReinstallCredentialProvider: true

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
- task: MSBuild@1
  inputs:
    solution: '**/*.sln'
    msbuildVersion: '15.0'
    clean: true
    restoreNugetPackages: true
    logProjectEvents: true
    createLogFile: true